# Welcome to Jekyll!
#

# Site settings
title: Spectral
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Chrystiann Lavarini # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: lavarini.c@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clavarini.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/clavarinigeo
  github: https://github.com/clavarini
  linkedin-square: https://linkedin.com/in/chrystiann-lavarini/
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
